# k8s/05-spark-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: bigdata-lab8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: bigdata-lab8
rules:
  - apiGroups: [""]
    resources: ["pods","pods/log","services","configmaps","persistentvolumeclaims"]
    verbs: ["get","list","watch","create","delete","patch","update"]
  - apiGroups: ["batch","extensions"]
    resources: ["jobs"]
    verbs: ["get","list","watch","create","delete","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: bigdata-lab8
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: bigdata-lab8
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

