apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: bigdata-lab8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: bigdata-lab8
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "configmaps", "secrets", "events", "persistentvolumeclaims"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications","scheduledsparkapplications"]
    verbs: ["get","list","watch","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: bigdata-lab8
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: bigdata-lab8
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
