apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab5-model
  namespace: bigdata-lab8
  labels:
    app: lab5-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab5-model
  template:
    metadata:
      labels:
        app: lab5-model
    spec:
      containers:
        - name: model
          image: docker.io/mitlyy/lab5-model:1.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: lab8-secrets
            - configMapRef:
                name: lab8-config
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

